"""add explanation and category fields

Revision ID: 526ef0966c5d
Revises: c8d519a4cacf
Create Date: 2025-03-12 00:34:09.740037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526ef0966c5d'
down_revision = 'c8d519a4cacf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))

    # Add initial categories
    category_table = sa.table('category',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('description', sa.String)
    )
    
    op.bulk_insert(category_table,
        [
            {'name': 'Mortgage/Rent', 'description': 'Housing expenses'},
            {'name': 'Credit Card', 'description': 'Credit card payments'},
            {'name': 'Food/Groceries', 'description': 'Food and grocery expenses'},
            {'name': 'Utilities', 'description': 'Utility bills'},
            {'name': 'Transportation', 'description': 'Transportation costs'},
            {'name': 'Entertainment', 'description': 'Entertainment expenses'},
            {'name': 'Healthcare', 'description': 'Medical and healthcare costs'},
            {'name': 'Insurance', 'description': 'Insurance payments'},
            {'name': 'Savings', 'description': 'Savings contributions'},
            {'name': 'Investments', 'description': 'Investment contributions'},
            {'name': 'Education', 'description': 'Education-related expenses'},
            {'name': 'Clothing', 'description': 'Clothing purchases'},
            {'name': 'Miscellaneous', 'description': 'Other expenses'}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('explanation')

    # Remove initial categories
    op.execute("DELETE FROM category WHERE name IN ("
               "'Mortgage/Rent', 'Credit Card', 'Food/Groceries', "
               "'Utilities', 'Transportation', 'Entertainment', "
               "'Healthcare', 'Insurance', 'Savings', 'Investments', "
               "'Education', 'Clothing', 'Miscellaneous')")
    # ### end Alembic commands ###
